# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "Install Python Requirements"
    command: |
      pip install -r requirements.txt
  
  - name: "Install Ubuntu Packages"
    command: |
      sudo apt-get update && sudo apt-get install -y vim wget iputils-ping net-tools netcat
     
